version: '3.2'
services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
   # restart: always
    volumes:
      - "${DATA_DIR}/mysql:/var/lib/mysql"
    environment: 
      MYSQL_ROOT_PASSWORD: password123zzzte

  nextcloud:
    image: nextcloud:${NEXTCLOUD_VERSION}
    container_name: nextcloud
   # restart: always
    volumes:
      - "${DATA_DIR}/nextcloud:/var/www/html"
      - "${DATA_DIR}/mysql:/var/lib/mysql"
    links:
      - mysql:mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: root
      MYSQL_PASSWORD: password123zzzte
      VIRTUAL_HOST: ${HOST}
      LETSENCRYPT_HOST: ${HOST}
    depends_on:
      - mysql

  reverse-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    # restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - "${DATA_DIR}/nginx/certs:/etc/nginx/certs:ro"
      - "${DATA_DIR}/nginx/vhosts:/etc/nginx/vhost.d"
      - "${DATA_DIR}/nginx/html:/usr/share/nginx/html"
      - ./nginx.conf:/etc/nginx/proxy.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
   # restart: always
    volumes:
      - "${DATA_DIR}/nginx/certs:/etc/nginx/certs"
      - "${DATA_DIR}/nginx/vhosts:/etc/nginx/vhost.d"
      - "${DATA_DIR}/nginx/html:/usr/share/nginx/html"
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - reverse-proxy


  onlyoffice:
    image: onlyoffice/documentserver
    container_name: onlyoffice
   # restart: always
    volumes:
      - "${DATA_DIR}/app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data"
      - "${DATA_DIR}/app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice"
      - "${DATA_DIR}/app/onlyoffice/DocumentServer/db:/var/lib/postgresql"
    ports:
      - 8080:443
    
    environment:
      SSL_CERTIFICATE_PATH: /etc/certs/cert.pem
      SSL_KEY_PATH: /etc/certs/privkey.pem
      SSL_DHPARAM_PATH: /etc/certs/dhparam.pem

